services:
  bot:
    build:
      context: .
    env_file: .env
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis

  scheduler:
    build:
      context: .
    env_file: .env
    command: celery -A scheduler.tasks worker -B -l info
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: