version: "3.9"
services:
  bot:
    build: .
    command: python -m bot.main
    env_file: .env
    depends_on: [db, redis]
  scheduler:
    build: .
    command: celery -A scheduler.tasks worker -B -l info
    env_file: .env
    depends_on: [db, redis]
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    restart: unless-stopped
volumes:
  pgdata: