version: '3.8'
services:
  bot:
    build: .
    command: python -m bot.main
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
    depends_on:
      - db
      - redis

  scheduler:
    build: .
    command: celery -A scheduler.tasks worker -B -l info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai
    volumes:
      - db-data: /var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data: /data