version: "3.9"
services:
  bot:
    build: .
    env_file: .env
    ports:
      - "80:8000"
  scheduler:
    build: .
    env_file: .env
    command: celery -A scheduler.tasks worker -B -l info
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: --interval 30